# Generated by Django 2.1.4 on 2020-03-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_truename', models.CharField(max_length=255)),
                ('u_phone', models.CharField(max_length=255, unique=True)),
                ('u_password', models.CharField(max_length=255)),
                ('u_house_number', models.CharField(max_length=255)),
                ('u_car_number', models.CharField(max_length=255, null=True, unique=True)),
                ('u_face', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
